---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: installresources.gocd.gloriousgloria
spec:
  group: gocd.gloriousgloria
  scope: Namespaced
  names:
    plural: installresources
    singular: installresource
    kind: InstallResource
    shortNames: 
    - ir
    - irs
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # crds properties
              required: [ "sdmeta", "relatedobject", "gitlabpointer" ]
              properties:
                sdmeta: 
                  type: object
                  required: ["namespace", "name"]
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                relatedobject: 
                  type: array
                  items:
                    type: object
                    required: ["objecttype","apiversion","namespace","name"]
                    properties:
                      objecttype:
                        type: string
                      apiversion:
                        type: string
                      namespace:
                        type: string
                      name:
                        type: string
                gitlabpointer:
                  type: array
                  items:
                    type: object
                    required: ["gitlabapiv4", "projectid", "accesstoken", "file"]
                    properties:
                      gitlabapiv4:
                        type: string
                      projectid:
                        type: integer
                      accesstoken: 
                        type: string
                      file: 
                        type: string

