---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templatesets.gocd.gloriousgloria
spec:
  group: gocd.gloriousgloria
  scope: Namespaced
  names:
    plural: templatesets
    singular: templateset
    kind: TemplateSet
    shortNames: 
    - ts
    - tss
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # crds properties
              required: [ "content" ]
              properties:
                content: 
                  type: string
